#!/bin/sh
echo "Please enter Teslacam Date Time Prefix i.e. 2022-04-20_20-06-48"
read cam_date
echo "The Input Date is $cam_date"
front="$cam_date-front.mp4"
left="$cam_date-left_repeater.mp4"
back="$cam_date-back.mp4"
right="$cam_date-right_repeater.mp4"
outputfile="$cam_date-combined.mp4"
echo "Front Cam File is $front"
echo " Back Cam File is $back"
echo " Left Cam File is $left"
echo "Right Cam File is $right"
echo "   Output File is $outputfile"
echo "Press Any Key to Proceed"
read ready

./ffmpeg -i $left -i $back -i $right -i $front -filter_complex "[0:v][1:v][2:v]hstack=inputs=3[v01];[v01]scale=1280:-1[v03];[3:v][v03]vstack=inputs=2[v]" -map "[v]" $outputfile
